### PR TITLE
Implement enums

### PR DESCRIPTION
**Pull request by elguitarraverde**
Implement enums

@gnovaro I need help. I don't know how to create a migration to update the constants of the enum field of the 'lead' table. I need to add 'in_progress' and 'converted'

```php
$table->enum('status', ['open', 'first_contact', 'recall', 'quote', 'quoted', 'waiting_for_answer', 'standby', 'closed'])->nullable()->default('open')->after('country_id');  
>>>>>>> ADD 'in_progress' and 'converted' in a new migration <<<<<<<<<<
```

undefined in_progress constant in migrations. #78

### CODE REVIEW

**Comment by gnovaro** [comment]
I updated the branch from master

**Comment by gnovaro** [comment]
> Implement enums
> 
> @gnovaro I need help. I don't know how to create a migration to update the constants of the enum field of the 'lead' table. I need to add 'in_progress' and 'converted'
> 
> ```
> $table->enum('status', ['open', 'first_contact', 'recall', 'quote', 'quoted', 'waiting_for_answer', 'standby', 'closed'])->nullable()->default('open')->after('country_id');  
> >>>>>>> ADD 'in_progress' and 'converted' in a new migration <<<<<<<<<<
> ```
> 
> undefined in_progress constant in migrations. #78

For solve this is easy is just create a migration like this
`php artisan make:migration alter_table_lead_add_missing_status`

public function up()
    {
        Schema::table('lead', function (Blueprint $table) {
            $table->enum('status', ['open', 'first_contact', 'recall', 'quote', 'quoted', 'waiting_for_answer','in_progress', 'standby',  'closed', 'converted'])->nullable()->default('open')->change();
        });
    }

This should be works the important here is the ->change method at the end of the call with this laravel kowns is an alter off a column already exist. For this works we need to have installed a specify package from doctrine but i think we already used this before...

**Comment by elguitarraverde** [comment]
it does not work. It seems to me that with enum types the change() method does not work.

https://42coders.com/changing-enum-column-in-laravel-migration

image

**Comment by gnovaro** [comment]
Ok dont worry, we proceed with the DB::query !

> it does not work. It seems to me that with enum types the change() method does not work.
> 
> https://42coders.com/changing-enum-column-in-laravel-migration
> 
> image

**Comment by elguitarraverde** [comment]
I have not been able to manage to modify the items in the status column without losing the data stored in that field.

The quick solution is to change the column type from 'enum' to 'string', this way it is more flexible to changes and no data is lost in the migration.

**Comment by elguitarraverde** [comment]
We will return to the topic later.

**Pull request closed without merging**
